### ISSUE TITLE
init/초기 환경 설정

### ISSUE THREAD

**Issue by OOixn** [codeZ-IDE/frontend#2]
* 적용 페이지 : 없음

## 내용
초기 환경 설정

## TODO
- [x] 개발 버전 통일
- [x] eslint, prttier 설정 통일
- [x] 디렉토리 구조 설정
