### ISSUE TITLE
codeZ UI 생성

### ISSUE THREAD

**Issue by OOixn** [codeZ-IDE/frontend#4]
* 적용 페이지 : 모든 페이지 

## TODO
- [ ] 로그인 페이지
- [ ] 회원가입 페이지
- [ ] 메인 페이지
- [ ] 문제 상세 페이지
- [ ] 상점 페이지
- [ ] 랭킹 페이지
- [ ] 게시판 페이지
- [ ] 게시판 상세 페이지
- [ ] 퀘스트 페이지
- [ ] 유저 프로필 모달
- [ ] 내 정보 모달 
- [ ] 마이 페이지_스크랩 탭
- [ ] 마이 페이지_커뮤니티 탭
- [ ] 마이 페이지_업적 탭
- [ ] 마이 페이지_문제 출제 탭
